name: Coverage


on:
  push:
    branches:    
      - badges

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install coverage 

      - name: Update coverage badge
        run: |
          coverage run -m unittest discover
          coverage report 
          coverage xml
      - name: Commit changes
        run: |
          git add .
          git commit -m "updated coverage xml"
          git push origin badges
