name: Coverage

on:
  workflow_call

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v3
        with:
          ref: badges
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt