name: Coverage

on:
  workflow_call

jobs:

  coverage:
    uses: ./.github/workflows/coverage.yaml
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: badges
      - name: test_echo
        run: |
          echo "testing"
          
