name: Coverage

on:
  workflow_call

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v3
        with:
          ref: badges

      - name: test_echo
        run: |
          echo "testing" >> test.txt