name: Coverage


on:
  push:
    branches:    
      - badges

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install coverage 

      - name: Update coverage badge
        run: |
          coverage run -m unittest discover
          coverage report 
          coverage xml

      - name: Configure Git
        run: |
          cat $GITHUB_ACTOR
      #     git config --global user.name "${{ github_actor }}"
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com>"

      # - name: Commit changes
      #   run: |
      #     git add .
      #     git commit -m "Updated coverage XML"
      #     git push origin badges