name: Documentation up to date

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Install Sphinx (or any other dependencies needed for building the docs)
          pip install sphinx
          pip install sphinx-rtd-theme

      - name: Update Documentation
        run: |
          # Generate the API documentation using sphinx-apidoc
          sphinx-apidoc . -o docs/
          make -C docs html

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: main
