name: Update Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Use gh-pages branch
        uses: actions/checkout@gh-pages

      - name: Install dependencies
        run: |
          # Install Sphinx (or any other dependencies needed for building the docs)
          pip install sphinx
          pip install sphinx-rtd-theme

      - name: Update Documentation
        run: |
          # Generate the API documentation using sphinx-apidoc
          sphinx-apidoc . -o docs/

      - name: Commit changes
        run: |
          git branch
          git checkout gh-pages
          git pull origin main --rebase
          git add .
          git commit -m "Update documentation"
          git push

